apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ping-pong
  name: ping-pong
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: log-folder
          persistentVolumeClaim:
            claimName: log-pvc
      containers:
      - image: jmandl/ping-pong:0.3
        name: ping-pong
        volumeMounts:
          - name: log-folder
            mountPath: /app/ping-pong
        resources: {}
status: {}
