apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pvc
  namespace: exercises
spec:
  storageClassName: ping-pong-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi