apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ping-pong
  name: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ping-pong
    spec:
      containers:
      - image: jmandl/ping-pong:0.2
        name: ping-pong
        resources: {}
status: {}
