apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ping-pong
  name: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ping-pong
    spec:
      containers:
      - image: jmandl/ping-pong:3.2.7
        name: ping-pong
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: pingpong-cm
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: pingpong-cm
              key: DB_PASSWORD
        resources: {}
status: {}
