apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ping-pong
  name: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ping-pong
    spec:
      containers:
      - image: jmandl/ping-pong:0.4
        name: ping-pong
        imagePullPolicy: Always
        volumeMounts:
        - name: file-volume
          mountPath: /app/static/
        env:
        - name: MESSAGE
          valueFrom:
            configMapKeyRef:
              name: pingpong-message-config
              key: message
        resources: {}
      volumes:
        - name: file-volume
          configMap:
            name: pingpong-file-config
status: {}
