apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: log-output
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: log-output
    spec:
      containers:
      - image: jmandl/log_output:0.1
        name: log-output-jwnjz
        resources: {}
status: {}
