apiVersion: v1
kind: PersistentVolume
metadata:
  name: ping-pong-pv
  namespace: exercises
spec:
  storageClassName: ping-pong-pv
  capacity:
    storage: 1Gi 
  volumeMode: Filesystem 
  accessModes:
  - ReadWriteOnce
  local:
    path: /tmp/ping-pong
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3d-k3s-default-agent-0