apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes: 
        - name: shared-folder
          emptyDir: {}
      containers:
        - name: todo-app
          imagePullPolicy: Always
          image: jmandl/todo-app:1.3
          ports:
          - containerPort: 5000
